2017.06.19_HomeWork
bugslayer312/CppStudentHomeWorks pull request #11
Opened 2017-06-26 18:44 UTC by alisatsar

2017-07-03 07:48 UTC, bugslayer312 requested changes

2017-07-03 07:48 UTC, bugslayer312 commented on Tsarova Alisa/2017.06.19_HomeWork/2017.06.19_HomeWork/DynArray.h
> +	T* index = nullptr;
Сделать приватным, инициализацию перенести в конструктор

2017-07-03 07:48 UTC, bugslayer312 commented on Tsarova Alisa/2017.06.19_HomeWork/2017.06.19_HomeWork/DynArray.h
> +		if (ptr == it.index)
У вас в классе итератор уже реализован оператор ==, который проверяет на равенство внутренние указатели (index). Используйте его.

2017-07-03 07:48 UTC, bugslayer312 commented on Tsarova Alisa/2017.06.19_HomeWork/2017.06.19_HomeWork/DynArray.h
> +		reserve(m_capacity);
Резервируйте память по такому же правилу как в PushBack

2017-07-03 07:48 UTC, bugslayer312 commented on Tsarova Alisa/2017.06.19_HomeWork/2017.06.19_HomeWork/DynArray.h
> +		reserve(m_capacity);
Резервируйте память по такому же правилу как в PushBack

2017-07-03 07:48 UTC, bugslayer312 commented on Tsarova Alisa/2017.06.19_HomeWork/2017.06.19_HomeWork/DynArray.h
> +	if (index < m_size && index >= 0)
А если нет ? Выдайте сообщение об ошибке + exit()

2017-07-03 07:48 UTC, bugslayer312 commented on Tsarova Alisa/2017.06.19_HomeWork/2017.06.19_HomeWork/DynArray.h
> +		exit(1);
Добавить сообщение об ошибке

2017-07-03 07:48 UTC, bugslayer312 commented on Tsarova Alisa/2017.06.19_HomeWork/2017.06.19_HomeWork/DynArray.h
> +	if (index < m_size && index >= 0)
А если нет ? Выдайте сообщение об ошибке + exit()

2017-07-03 07:48 UTC, bugslayer312 commented on Tsarova Alisa/2017.06.19_HomeWork/2017.06.19_HomeWork/DynArray.h
> +		reserve(m_capacity);
Выделяйте память по такому же правилу, как в PopBack()

2017-07-06 19:37 UTC, bugslayer312 approved these changes

2017-07-06 19:37 UTC, merged

2017-07-11 19:09 UTC, alisatsar commented
Вы спрашивали: Calculator(Operation* operation)
Для чего вам нужен этот параметр в конструкторе ?

без него не работает метод ShowMenu()
Возможно вы мне покажите как можно связать класс Calculator с наследниками класса Operations, я нашла только такой способ